name: Build and push docker image

on:
    push:
        branches:
        - develop

    pull_request:
        branches:
        - develop

jobs:
    build-and-push:
        runs-on: ubuntu-latest

        steps:
        # 1. Checkout del código
        - name: Checkout repository
          uses: actions/checkout@v3

        # 2. Loguearse en Docker Hub
        - name: Log in to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}

        # 3. Construir la imagen de Docker
        - name: Build Docker Image
          run: |
            docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:latest .
        
        # 4. Push de la imagen a Docker Hub
        - name: Push Docker Image
          run: |
            docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest